// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Traffic Light State Machine
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

#include "AwryLink.h"

#define LIGHT_AMBER 2
#define LIGHT_GREEN 1
#define LIGHT_RED 0
// State machine "light": Red, Green, Amber
bool waiting = false;
uint8_t light = 0;

// Variables exposed to the ArduForge dashboard.
static const AwryVar AWRY_VARS[] = {
  { "waiting", (void *)&waiting, AWRY_BOOL, true },
};
static const char AWRY_HASH[] = "7e6b41e0";

void _af_isr_n6();

void setup() {
  Serial.begin(115200);
  attachInterrupt(digitalPinToInterrupt(2), _af_isr_n6, FALLING);
  awrylink_begin(AWRY_VARS, 1, AWRY_HASH);
  pinMode(11, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(13, OUTPUT);
  pinMode(11, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(13, OUTPUT);
}

void loop() {
  awrylink_poll();
  static unsigned long _af_last_n9 = 0;
  if (millis() - _af_last_n9 >= (unsigned long)(1000)) {
    _af_last_n9 = millis();
    switch (light) {
      case 0: // Red
      digitalWrite(11, HIGH);
      digitalWrite(13, LOW);
      digitalWrite(12, LOW);
      light = LIGHT_GREEN;
        break;
      case 1: // Green
      digitalWrite(13, HIGH);
      digitalWrite(12, LOW);
      digitalWrite(11, LOW);
      light = LIGHT_AMBER;
        break;
      case 2: // Amber
      digitalWrite(12, HIGH);
      digitalWrite(11, LOW);
      digitalWrite(13, LOW);
      light = LIGHT_RED;
        break;
    }
  }
}

void _af_isr_n6() {
  waiting = true;
}
