// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Arrays
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

int counter = 10;
int samples[5];

void setup() {
  samples[0] = 7;
  Serial.begin(9600);
}

void loop() {
  Serial.print("value");
  Serial.print(": ");
  Serial.println(String(samples[1]));
  Serial.print("length");
  Serial.print(": ");
  Serial.println(String((int)(sizeof(samples) / sizeof(samples[0]))));
  counter -= 1.0f;
}
