// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: NeoPixel Studio
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

#include "AwryLink.h"
#include <Adafruit_NeoPixel.h>

Adafruit_NeoPixel pixels(8, 6, NEO_GRB + NEO_KHZ800);
int blue = 0;
int brightness = 64;
int green = 0;
int red = 255;

// Variables exposed to the ArduForge dashboard.
static const AwryVar AWRY_VARS[] = {
  { "blue", (void *)&blue, AWRY_INT, true },
  { "brightness", (void *)&brightness, AWRY_INT, true },
  { "green", (void *)&green, AWRY_INT, true },
  { "red", (void *)&red, AWRY_INT, true },
};
static const char AWRY_HASH[] = "1b1fb7ea";

void setup() {
  Serial.begin(115200);
  awrylink_begin(AWRY_VARS, 4, AWRY_HASH);
  pixels.begin();
  pixels.show();
}

void loop() {
  awrylink_poll();
  static unsigned long _af_last_n8 = 0;
  if (millis() - _af_last_n8 >= (unsigned long)(50)) {
    _af_last_n8 = millis();
    pixels.setBrightness(brightness);
    pixels.fill(pixels.Color(red, green, blue));
    pixels.show();
  }
}
