// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Stopwatch
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

bool _af_sw_running_run = false;
unsigned long _af_sw_start_run = 0;
unsigned long _af_sw_total_run = 0;

void setup() {
  if (!_af_sw_running_run) {
    _af_sw_start_run = millis();
    _af_sw_running_run = true;
  }
}

void loop() {
  Serial.print("elapsed");
  Serial.print(": ");
  Serial.println(String((long)(_af_sw_total_run + (_af_sw_running_run ? millis() - _af_sw_start_run : 0))));
  Serial.print("since");
  Serial.print(": ");
  Serial.println(String((long)(millis() - (unsigned long)(0))));
}
