// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Temperature Logger
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

#include "AwryLink.h"
#include <DHT.h>
#include <LiquidCrystal_I2C.h>
#include <Wire.h>

DHT dht_n11(4, DHT22);
DHT dht_n12(4, DHT22);
LiquidCrystal_I2C lcd(0x27, 16, 2);
float humidity = 0.0f;
float tempC = 0.0f;

// Variables exposed to the ArduForge dashboard.
static const AwryVar AWRY_VARS[] = {
  { "humidity", (void *)&humidity, AWRY_FLOAT, true },
  { "tempC", (void *)&tempC, AWRY_FLOAT, true },
};
static const char AWRY_HASH[] = "26643b11";

void setup() {
  Serial.begin(115200);
  awrylink_begin(AWRY_VARS, 2, AWRY_HASH);
  dht_n11.begin();
  dht_n12.begin();
  lcd.init();
  lcd.backlight();
}

void loop() {
  awrylink_poll();
  static unsigned long _af_last_n6 = 0;
  if (millis() - _af_last_n6 >= (unsigned long)(2000)) {
    _af_last_n6 = millis();
    tempC = dht_n11.readTemperature();
    humidity = dht_n12.readHumidity();
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print("Temp C:");
  }
}
