// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: ServoComponent
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

#include <Servo.h>

Servo servo_arm;

void setup() {
  servo_arm.attach(9);
}

void loop() {
  servo_arm.write(120);
  servo_arm.writeMicroseconds(1750);
  servo_arm.detach();
}
