// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Servo Control Panel
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

#include "AwryLink.h"
#include <Servo.h>

Servo servo_servo;
int angle = 90;

// Variables exposed to the ArduForge dashboard.
static const AwryVar AWRY_VARS[] = {
  { "angle", (void *)&angle, AWRY_INT, true },
};
static const char AWRY_HASH[] = "4d1fa6a1";

void setup() {
  Serial.begin(115200);
  awrylink_begin(AWRY_VARS, 1, AWRY_HASH);
  servo_servo.attach(9);
}

void loop() {
  awrylink_poll();
  static unsigned long _af_last_n5 = 0;
  if (millis() - _af_last_n5 >= (unsigned long)(50)) {
    _af_last_n5 = millis();
    servo_servo.write(angle);
  }
}
