// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Sequence
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

void setup() {
  // Nothing to do at startup.
}

void loop() {
  // step 1
    digitalWrite(2, HIGH);
  // step 2
    digitalWrite(3, HIGH);
  // step 3
    digitalWrite(4, HIGH);
}
