// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Literals
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

void setup() {
  // Nothing to do at startup.
}

void loop() {
  delay(42);
  if (true) {
    analogWrite(9, 1.5f);
  } else {
    // nothing connected
  }
}
