/*
 * AwryLink — live link between an ArduForge sketch and the dashboard.
 * Protocol and constraints: BUILD_PLAN.md §Phase 6, Mode B.
 *
 * Rules this implementation is bound by, all of them because the Uno has 2KB
 * of SRAM and a program that fragments the heap will die after hours of use:
 *
 *   - Never block. No delay() anywhere in the link handler.
 *   - No dynamic allocation and no String in the hot path.
 *   - Frames are built in a fixed char buffer with snprintf and truncated
 *     rather than overflowed.
 *   - A telemetry frame that would exceed the line budget is split across
 *     frames round-robin, so no variable is ever starved.
 */
#ifndef AWRYLINK_H
#define AWRYLINK_H

#include <Arduino.h>

/** Longest line, in either direction (§Phase 6). */
#define AWRYLINK_MAX_LINE 128

/** Telemetry cannot be requested faster than this. */
#define AWRYLINK_MIN_INTERVAL_MS 50

enum AwryVarType : uint8_t {
  AWRY_INT = 0,
  AWRY_LONG = 1,
  AWRY_FLOAT = 2,
  AWRY_BOOL = 3,
};

/**
 * One exposed variable. The table is generated by codegen and lives in static
 * storage; AwryLink never copies or owns it.
 */
struct AwryVar {
  const char *name;
  void *ptr;
  AwryVarType type;
  bool writable;
};

/**
 * Registers the variable table. Call once from setup(), after Serial.begin().
 * `sketchHash` lets the host notice it is talking to a different build.
 */
void awrylink_begin(const AwryVar *table, uint8_t count, const char *sketchHash);

/**
 * Services the link: parses whatever has arrived and emits telemetry when due.
 * Codegen emits this as the first statement of loop(). Returns immediately if
 * there is nothing to do.
 */
void awrylink_poll();

/** Sends a user log line to the dashboard as an `L|` frame. */
void awrylink_log(const char *text);

#endif  // AWRYLINK_H
