// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Motor Speed Controller
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

#include "AwryLink.h"

int leftSpeed = 0;
int rightSpeed = 0;

// Variables exposed to the ArduForge dashboard.
static const AwryVar AWRY_VARS[] = {
  { "leftSpeed", (void *)&leftSpeed, AWRY_INT, true },
  { "rightSpeed", (void *)&rightSpeed, AWRY_INT, true },
};
static const char AWRY_HASH[] = "2b0f071e";

void setup() {
  Serial.begin(115200);
  awrylink_begin(AWRY_VARS, 2, AWRY_HASH);
  pinMode(10, OUTPUT);
  pinMode(5, OUTPUT);
  pinMode(6, OUTPUT);
  pinMode(7, OUTPUT);
  pinMode(8, OUTPUT);
  pinMode(9, OUTPUT);
  // nothing connected
}

void loop() {
  awrylink_poll();
  static unsigned long _af_last_n5 = 0;
  if (millis() - _af_last_n5 >= (unsigned long)(50)) {
    _af_last_n5 = millis();
    digitalWrite(6, leftSpeed >= 0 ? HIGH : LOW);
    digitalWrite(7, leftSpeed >= 0 ? LOW : HIGH);
    analogWrite(5, constrain(abs(leftSpeed), 0, 255));
    digitalWrite(8, rightSpeed >= 0 ? HIGH : LOW);
    digitalWrite(9, rightSpeed >= 0 ? LOW : HIGH);
    analogWrite(10, constrain(abs(rightSpeed), 0, 255));
  }
}
