// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Blink
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

void setup() {
  pinMode(13, OUTPUT);
  pinMode(13, OUTPUT);
}

void loop() {
  static unsigned long _af_last_n4 = 0;
  if (millis() - _af_last_n4 >= (unsigned long)(500)) {
    _af_last_n4 = millis();
    digitalWrite(13, !digitalRead(13));
  }
}
