// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Button + LED
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

#include "AwryLink.h"

bool ledOn = false;

// Variables exposed to the ArduForge dashboard.
static const AwryVar AWRY_VARS[] = {
  { "ledOn", (void *)&ledOn, AWRY_BOOL, true },
};
static const char AWRY_HASH[] = "9efb71af";

bool _af_press_n6(uint8_t buttonPin, unsigned long settleMs);

void setup() {
  Serial.begin(115200);
  awrylink_begin(AWRY_VARS, 1, AWRY_HASH);
  pinMode(2, INPUT_PULLUP);
  pinMode(13, OUTPUT);
}

void loop() {
  awrylink_poll();
  if (_af_press_n6(2, 25)) {
    ledOn = (!ledOn);
    digitalWrite(13, ledOn);
  } else {
    // nothing connected
  }
}

bool _af_press_n6(uint8_t buttonPin, unsigned long settleMs) {
  static bool wasDown = false;
  static unsigned long changedAt = 0;

  bool isDown = (digitalRead(buttonPin) == LOW);
  if (isDown != wasDown && millis() - changedAt >= settleMs) {
    changedAt = millis();
    wasDown = isDown;
    return isDown;
  }
  return false;
}
