// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: LcdComponent
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

#include <LiquidCrystal_I2C.h>
#include <Wire.h>

LiquidCrystal_I2C lcd(0x27, 16, 2);

void setup() {
  lcd.init();
  lcd.backlight();
}

void loop() {
  lcd.clear();
  lcd.setCursor(3, 1);
  lcd.print("Ready");
  if (true) { lcd.backlight(); } else { lcd.noBacklight(); }
}
