import { Eraser, Hash, Terminal, TerminalSquare, Type } from 'lucide-react';
import type { NodeDef } from '@/nodes/types';

export const serialNodes: readonly NodeDef[] = [
  {
    id: 'serial.begin',
    category: 'serial',
    label: 'Serial Begin',
    description: 'Starts the serial link. Put this in setup, before any printing.',
    icon: Terminal,
    kind: 'statement',
    execIn: true,
    execOut: ['then'],
    config: [
      {
        kind: 'select',
        id: 'baud',
        label: 'Baud',
        default: '115200',
        options: [
          { value: '9600', label: '9600' },
          { value: '57600', label: '57600' },
          { value: '115200', label: '115200' },
        ],
      },
    ],
    summary: (v) => `begin ${v['baud'] ?? '115200'}`,
    emit: (ctx) => ({ statements: `Serial.begin(${String(ctx.config('baud'))});` }),
  },
  {
    id: 'serial.print',
    category: 'serial',
    label: 'Serial Print',
    description: 'Prints a value without moving to a new line.',
    icon: TerminalSquare,
    kind: 'statement',
    execIn: true,
    execOut: ['then'],
    inputs: [
      { id: 'value', label: 'Value', type: 'string', literal: { kind: 'string', default: '', placeholder: 'text' } },
    ],
    summary: (v) => `print "${String(v['value'] ?? '')}"`,
    emit: (ctx) => ({ statements: `Serial.print(${ctx.input('value')});` }),
  },
  {
    id: 'serial.println',
    category: 'serial',
    label: 'Serial Println',
    description: 'Prints a value and moves to the next line.',
    icon: TerminalSquare,
    kind: 'statement',
    execIn: true,
    execOut: ['then'],
    inputs: [
      { id: 'value', label: 'Value', type: 'string', literal: { kind: 'string', default: 'hello', placeholder: 'text to print' } },
    ],
    summary: (v) => `print "${String(v['value'] ?? '')}"`,
    emit: (ctx) => ({ statements: `Serial.println(${ctx.input('value')});` }),
  },
  {
    id: 'serial.printValue',
    category: 'serial',
    label: 'Print Labelled Value',
    description: 'Prints "label: value", which is much easier to read in the monitor.',
    icon: Type,
    kind: 'statement',
    execIn: true,
    execOut: ['then'],
    inputs: [
      { id: 'label', label: 'Label', type: 'string', literal: { kind: 'string', default: 'value' } },
      { id: 'value', label: 'Value', type: 'string', literal: { kind: 'string', default: '' } },
    ],
    summary: (v) => `${String(v['label'] ?? 'value')}: …`,
    emit: (ctx) => ({
      statements: [
        `Serial.print(${ctx.input('label')});`,
        `Serial.print(": ");`,
        `Serial.println(${ctx.input('value')});`,
      ].join('\n'),
    }),
  },
  {
    id: 'serial.available',
    category: 'serial',
    label: 'Serial Available',
    description: 'How many bytes have arrived and are waiting to be read.',
    icon: Hash,
    kind: 'expression',
    outputs: [{ id: 'out', label: 'Bytes', type: 'int' }],
    summary: () => 'bytes waiting',
    emit: () => ({ expression: 'Serial.available()' }),
  },
  {
    id: 'serial.read',
    category: 'serial',
    label: 'Serial Read',
    description: 'Reads one waiting byte. Returns -1 when nothing is waiting.',
    icon: Terminal,
    kind: 'expression',
    outputs: [{ id: 'out', label: 'Byte', type: 'int' }],
    summary: () => 'read byte',
    emit: () => ({ expression: 'Serial.read()' }),
  },
  {
    id: 'serial.readStringUntil',
    category: 'serial',
    label: 'Serial Read Line',
    description: 'Reads incoming text up to a terminator character.',
    icon: Type,
    kind: 'expression',
    inputs: [
      {
        id: 'terminator',
        label: 'Ends with',
        type: 'string',
        literal: {
          kind: 'select',
          default: '\\n',
          options: [
            { value: '\\n', label: 'newline' },
            { value: '\\r', label: 'carriage return' },
            { value: ',', label: 'comma' },
          ],
        },
      },
    ],
    outputs: [{ id: 'out', label: 'Text', type: 'string' }],
    summary: () => 'read line',
    emit: (ctx) => {
      // The select supplies a bare escape sequence, which must become a char literal.
      const raw = ctx.input('terminator').replace(/^"|"$/g, '');
      return { expression: `Serial.readStringUntil('${raw}')` };
    },
  },
  {
    id: 'serial.parseInt',
    category: 'serial',
    label: 'Serial Parse Number',
    description: 'Reads the next whole number from the incoming text.',
    icon: Hash,
    kind: 'expression',
    outputs: [{ id: 'out', label: 'Value', type: 'int' }],
    summary: () => 'parse int',
    emit: () => ({ expression: 'Serial.parseInt()' }),
  },
  {
    id: 'serial.parseFloat',
    category: 'serial',
    label: 'Serial Parse Decimal',
    description: 'Reads the next decimal number from the incoming text.',
    icon: Hash,
    kind: 'expression',
    outputs: [{ id: 'out', label: 'Value', type: 'float' }],
    summary: () => 'parse float',
    emit: () => ({ expression: 'Serial.parseFloat()' }),
  },
  {
    id: 'serial.flush',
    category: 'serial',
    label: 'Serial Flush',
    description: 'Waits until everything queued has finished sending.',
    icon: Eraser,
    kind: 'statement',
    execIn: true,
    execOut: ['then'],
    summary: () => 'flush',
    emit: () => ({ statements: 'Serial.flush();' }),
  },
];
