import { ALargeSmall, Equal, Hash, Link2, Scissors, Search, Type } from 'lucide-react';
import type { NodeDef, PortDef } from '@/nodes/types';

const textIn = (id: string, label: string, def = ''): PortDef => ({
  id,
  label,
  type: 'string',
  literal: { kind: 'string', default: def },
});

export const textNodes: readonly NodeDef[] = [
  {
    id: 'text.string',
    category: 'variables',
    label: 'Text',
    description: 'A fixed piece of text.',
    icon: Type,
    kind: 'expression',
    inputs: [
      { id: 'value', label: 'Text', type: 'string', literal: { kind: 'string', default: 'hello', placeholder: 'text' } },
    ],
    outputs: [{ id: 'out', label: 'Text', type: 'string' }],
    summary: (v) => `"${String(v['value'] ?? '')}"`,
    emit: (ctx) => ({ expression: ctx.input('value') }),
  },
  {
    id: 'text.concat',
    category: 'variables',
    label: 'Join Text',
    description: 'Sticks two pieces of text together.',
    icon: Link2,
    kind: 'expression',
    inputs: [textIn('a', 'First'), textIn('b', 'Second')],
    outputs: [{ id: 'out', label: 'Text', type: 'string' }],
    summary: () => 'a + b',
    emit: (ctx) => ({ expression: `(String(${ctx.input('a')}) + String(${ctx.input('b')}))` }),
  },
  {
    id: 'text.length',
    category: 'variables',
    label: 'Text Length',
    description: 'How many characters a piece of text has.',
    icon: Hash,
    kind: 'expression',
    inputs: [textIn('value', 'Text')],
    outputs: [{ id: 'out', label: 'Length', type: 'int' }],
    summary: () => 'length',
    emit: (ctx) => ({ expression: `(int)String(${ctx.input('value')}).length()` }),
  },
  {
    id: 'text.substring',
    category: 'variables',
    label: 'Part Of Text',
    description: 'Takes a slice out of a piece of text.',
    icon: Scissors,
    kind: 'expression',
    inputs: [
      textIn('value', 'Text'),
      { id: 'from', label: 'From', type: 'int', literal: { kind: 'number', default: 0, integer: true } },
      { id: 'to', label: 'To', type: 'int', literal: { kind: 'number', default: 1, integer: true } },
    ],
    outputs: [{ id: 'out', label: 'Text', type: 'string' }],
    summary: (v) => `chars ${v['from'] ?? 0}..${v['to'] ?? 0}`,
    emit: (ctx) => ({
      expression: `String(${ctx.input('value')}).substring(${ctx.input('from')}, ${ctx.input('to')})`,
    }),
  },
  {
    id: 'text.indexOf',
    category: 'variables',
    label: 'Find In Text',
    description: 'Where a piece of text appears inside another. -1 when it does not.',
    icon: Search,
    kind: 'expression',
    inputs: [textIn('value', 'Text'), textIn('search', 'Look for')],
    outputs: [{ id: 'out', label: 'Position', type: 'int' }],
    summary: () => 'indexOf',
    emit: (ctx) => ({
      expression: `String(${ctx.input('value')}).indexOf(${ctx.input('search')})`,
    }),
  },
  {
    id: 'text.toInt',
    category: 'variables',
    label: 'Text To Number',
    description: 'Reads a whole number out of a piece of text.',
    icon: Hash,
    kind: 'expression',
    inputs: [textIn('value', 'Text', '0')],
    outputs: [{ id: 'out', label: 'Value', type: 'int' }],
    summary: () => 'to int',
    emit: (ctx) => ({ expression: `String(${ctx.input('value')}).toInt()` }),
  },
  {
    id: 'text.toFloat',
    category: 'variables',
    label: 'Text To Decimal',
    description: 'Reads a decimal number out of a piece of text.',
    icon: Hash,
    kind: 'expression',
    inputs: [textIn('value', 'Text', '0')],
    outputs: [{ id: 'out', label: 'Value', type: 'float' }],
    summary: () => 'to float',
    emit: (ctx) => ({ expression: `String(${ctx.input('value')}).toFloat()` }),
  },
  {
    id: 'text.toString',
    category: 'variables',
    label: 'Number To Text',
    description: 'Turns a number into text so it can be printed or joined.',
    icon: ALargeSmall,
    kind: 'expression',
    inputs: [{ id: 'value', label: 'Value', type: 'float', literal: { kind: 'number', default: 0 } }],
    outputs: [{ id: 'out', label: 'Text', type: 'string' }],
    summary: () => 'to text',
    emit: (ctx) => ({ expression: `String(${ctx.input('value')})` }),
  },
  {
    id: 'text.compare',
    category: 'variables',
    label: 'Text Equals',
    description: 'True when two pieces of text are exactly the same.',
    icon: Equal,
    kind: 'expression',
    inputs: [textIn('a', 'First'), textIn('b', 'Second')],
    outputs: [{ id: 'out', label: 'Same', type: 'bool' }],
    summary: () => 'a == b',
    emit: (ctx) => ({ expression: `(String(${ctx.input('a')}) == String(${ctx.input('b')}))` }),
  },
];
