// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Light-Seeking Servo
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

#include "AwryLink.h"
#include <Servo.h>

Servo servo_servo;
float gain = 0.05f;
int angle = 90;
int error = 0;

// Variables exposed to the ArduForge dashboard.
static const AwryVar AWRY_VARS[] = {
  { "angle", (void *)&angle, AWRY_INT, true },
  { "error", (void *)&error, AWRY_INT, true },
  { "gain", (void *)&gain, AWRY_FLOAT, true },
};
static const char AWRY_HASH[] = "3408503b";

void setup() {
  Serial.begin(115200);
  awrylink_begin(AWRY_VARS, 3, AWRY_HASH);
  servo_servo.attach(9);
}

void loop() {
  awrylink_poll();
  static unsigned long _af_last_n7 = 0;
  if (millis() - _af_last_n7 >= (unsigned long)(50)) {
    _af_last_n7 = millis();
    error = ((float)(analogRead(A0)) - (float)(analogRead(A1)));
    angle += ((float)(error) * gain);
    servo_servo.write(constrain((float)(angle), 0.0f, 180.0f));
  }
}
