// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: DhtComponent
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

#include <DHT.h>

DHT dht_n2(4, DHT11);
DHT dht_n3(7, DHT22);

void setup() {
  dht_n2.begin();
  dht_n3.begin();
}

void loop() {
  Serial.print("C");
  Serial.print(": ");
  Serial.println(String(dht_n2.readTemperature()));
  Serial.print("RH");
  Serial.print(": ");
  Serial.println(String(dht_n3.readHumidity()));
}
