// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: UserFunction
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

void blinkOnce();

void setup() {
  // Nothing to do at startup.
}

void loop() {
  blinkOnce();
}

void blinkOnce() {
  digitalWrite(13, HIGH);
  delay(50);
  digitalWrite(13, LOW);
}
