// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: NeoPixelComponent
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

#include <Adafruit_NeoPixel.h>

Adafruit_NeoPixel pixels(12, 5, NEO_GRB + NEO_KHZ800);

void setup() {
  pixels.begin();
  pixels.show();
  pixels.setBrightness(90);
}

void loop() {
  pixels.setPixelColor(2, pixels.Color(10, 200, 30));
  pixels.fill(pixels.Color(5, 5, 5));
  pixels.show();
}
