/**
 * Golden tests for the code generator (BUILD_PLAN.md §Phase 4).
 * All run with no hardware attached.
 */
import { beforeEach, describe, expect, it } from 'vitest';
import { generate } from '@/codegen/generate';
import { useGraphStore } from '@/store/graphStore';
import { resolveConnection } from '@/graph/connect';
import { allNodeDefs } from '@/nodes/registry';
import { sanitiseIdentifier, NameAllocator } from '@/codegen/names';
import { escapeCppString, formatFloat } from '@/codegen/literals';

const store = () => useGraphStore.getState();

function connect(source: string, sourceHandle: string, target: string, targetHandle: string): void {
  const result = resolveConnection({ source, sourceHandle, target, targetHandle }, store().nodes);
  if (!result.ok) throw new Error(`connect failed: ${result.reason}`);
  store().connect(result.edge);
}

function add(defId: string, x = 0, y = 0): string {
  const id = store().addNode(defId, { x, y });
  if (id === null) throw new Error(`could not add ${defId}`);
  return id;
}

function render(): string {
  const state = store();
  return generate(state.nodes, state.edges, { projectName: 'Blink' }).code;
}

beforeEach(() => {
  window.localStorage.clear();
  useGraphStore.setState({ nodes: [], edges: [], past: [], future: [], lastCommit: null });
  store().newProject();
});

/** On Loop -> Write(13,HIGH) -> Delay(500) -> Write(13,LOW) -> Delay(500) */
function buildBlink(): void {
  const loop = add('event.loop');
  const high = add('io.digitalWrite', 240);
  const wait1 = add('control.delay', 480);
  const low = add('io.digitalWrite', 720);
  const wait2 = add('control.delay', 960);
  connect(loop, 'exec-out:then', high, 'exec-in');
  connect(high, 'exec-out:then', wait1, 'exec-in');
  connect(wait1, 'exec-out:then', low, 'exec-in');
  connect(low, 'exec-out:then', wait2, 'exec-in');
  store().setLiteral(low, 'value', false);
}

describe('the Blink golden file', () => {
  it('matches the committed output exactly', () => {
    buildBlink();
    expect(render()).toBe(`// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Blink
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

void setup() {
  // Nothing to do at startup.
}

void loop() {
  digitalWrite(13, HIGH);
  delay(500);
  digitalWrite(13, LOW);
  delay(500);
}
`);
  });

  it('matches the plan reference when setup configures the pin', () => {
    // The §Phase 4 reference output, minus the named PIN_LED constant, which
    // needs a Declare Variable node (Phase 5f) to exist in the graph.
    const setup = add('event.setup');
    const pinMode = add('io.pinMode', 240);
    connect(setup, 'exec-out:then', pinMode, 'exec-in');
    buildBlink();

    expect(render()).toBe(`// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Blink
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

void setup() {
  pinMode(13, OUTPUT);
}

void loop() {
  digitalWrite(13, HIGH);
  delay(500);
  digitalWrite(13, LOW);
  delay(500);
}
`);
  });

  it('warns when a pin is driven without being set to OUTPUT', () => {
    buildBlink();
    const warnings = store().problems.filter((problem) => problem.severity === 'warning');
    expect(warnings.some((problem) => /never set to OUTPUT/i.test(problem.message))).toBe(true);
  });

  it('emits HIGH and LOW rather than true and false', () => {
    buildBlink();
    const code = render();
    expect(code).toContain('digitalWrite(13, HIGH);');
    expect(code).toContain('digitalWrite(13, LOW);');
    expect(code).not.toContain('true');
  });

  it('is deterministic across repeated generation', () => {
    buildBlink();
    expect(render()).toBe(render());
  });

  it('is deterministic regardless of node array order', () => {
    buildBlink();
    const forward = render();

    const state = store();
    useGraphStore.setState({ nodes: [...state.nodes].reverse(), edges: [...state.edges].reverse() });
    expect(render()).toBe(forward);
  });
});

describe('source map', () => {
  it('maps generated lines back to the node that produced them', () => {
    buildBlink();
    const state = store();
    const result = generate(state.nodes, state.edges, { projectName: 'Blink' });

    const digitalWriteLine = result.lines.findIndex((line) =>
      line.text.includes('digitalWrite(13, HIGH)'),
    );
    expect(digitalWriteLine).toBeGreaterThan(-1);

    const nodeId = result.sourceMap.get(digitalWriteLine + 1);
    expect(nodeId).toBeDefined();
    expect(result.nodeLines.get(nodeId!)).toContain(digitalWriteLine + 1);
  });

  it('never maps a line to a node that is not in the graph', () => {
    buildBlink();
    const state = store();
    const result = generate(state.nodes, state.edges);
    const ids = new Set(state.nodes.map((node) => node.id));
    for (const nodeId of result.sourceMap.values()) expect(ids.has(nodeId)).toBe(true);
  });
});

describe('setup and structure', () => {
  it('emits pinMode into setup from an On Setup chain', () => {
    const setup = add('event.setup');
    const pinMode = add('io.pinMode', 240);
    connect(setup, 'exec-out:then', pinMode, 'exec-in');

    const code = render();
    expect(code).toMatch(/void setup\(\) \{\n {2}pinMode\(13, OUTPUT\);\n\}/);
  });

  it('produces a compilable skeleton for an empty graph', () => {
    const code = render();
    expect(code).toContain('void setup() {');
    expect(code).toContain('void loop() {');
    expect(code).toContain('Add an On Loop node');
  });

  it('notes an unconnected branch rather than emitting an empty block', () => {
    const loop = add('event.loop');
    const branch = add('control.if', 240);
    connect(loop, 'exec-out:then', branch, 'exec-in');

    const code = render();
    expect(code).toContain('if (true) {');
    expect(code).toContain('// nothing connected');
  });

  it('does not hang on an execution cycle', () => {
    const loop = add('event.loop');
    const a = add('io.digitalWrite', 240);
    const b = add('io.digitalWrite', 480);
    connect(loop, 'exec-out:then', a, 'exec-in');
    connect(a, 'exec-out:then', b, 'exec-in');
    connect(b, 'exec-out:then', a, 'exec-in');

    const code = render();
    expect(code).toContain('loop in the execution chain stops here');
  });
});

describe('expressions and hoisting', () => {
  it('inlines a value used once', () => {
    const loop = add('event.loop');
    const delayNode = add('control.delay', 240);
    const analog = add('io.analogRead', 240, 200);
    connect(loop, 'exec-out:then', delayNode, 'exec-in');
    connect(analog, 'out:value', delayNode, 'in:ms');

    const code = render();
    expect(code).toContain('delay(analogRead(A0));');
    expect(code).not.toContain('_af_');
  });

  it('hoists a value consumed twice so it is read only once', () => {
    // analogRead() twice returns two different readings, so this is a
    // correctness requirement, not an optimisation (§Phase 4 step 3).
    const loop = add('event.loop');
    const first = add('control.delay', 240);
    const second = add('control.delay', 480);
    const analog = add('io.analogRead', 0, 200);
    connect(loop, 'exec-out:then', first, 'exec-in');
    connect(first, 'exec-out:then', second, 'exec-in');
    connect(analog, 'out:value', first, 'in:ms');
    connect(analog, 'out:value', second, 'in:ms');

    const code = render();
    expect(code).toMatch(/const int _af_\w+ = analogRead\(A0\);/);
    expect(code.match(/analogRead\(A0\)/g)).toHaveLength(1);
  });

  it('does not hoist a plain literal used twice', () => {
    const loop = add('event.loop');
    const first = add('control.delay', 240);
    const second = add('control.delay', 480);
    const number = add('math.number', 0, 200);
    connect(loop, 'exec-out:then', first, 'exec-in');
    connect(first, 'exec-out:then', second, 'exec-in');
    connect(number, 'out:out', first, 'in:ms');
    connect(number, 'out:out', second, 'in:ms');

    expect(render()).not.toContain('_af_');
  });

  it('wraps a numeric value in String() when it feeds a text input', () => {
    const loop = add('event.loop');
    const print = add('serial.println', 240);
    const analog = add('io.analogRead', 0, 200);
    connect(loop, 'exec-out:then', print, 'exec-in');
    connect(analog, 'out:value', print, 'in:value');

    expect(render()).toContain('Serial.println(String(analogRead(A0)));');
  });

  it('passes a value through a reroute point unchanged', () => {
    const loop = add('event.loop');
    const delayNode = add('control.delay', 480);
    const analog = add('io.analogRead', 0, 200);
    connect(loop, 'exec-out:then', delayNode, 'exec-in');
    connect(analog, 'out:value', delayNode, 'in:ms');

    const edge = store().edges.find((candidate) => candidate.data?.kind === 'data');
    expect(edge).toBeDefined();
    store().addReroute(edge!.id, { x: 300, y: 200 });

    expect(render()).toContain('delay(analogRead(A0));');
  });

  it('quotes and escapes string literals', () => {
    const loop = add('event.loop');
    const print = add('serial.println', 240);
    connect(loop, 'exec-out:then', print, 'exec-in');
    store().setLiteral(print, 'value', 'say "hi"\\path');

    expect(render()).toContain('Serial.println("say \\"hi\\"\\\\path");');
  });

  it('respects the comparison operator chosen in the inspector', () => {
    const loop = add('event.loop');
    const branch = add('control.if', 240);
    const compare = add('logic.compare', 0, 200);
    connect(loop, 'exec-out:then', branch, 'exec-in');
    connect(compare, 'out:out', branch, 'in:condition');
    store().setConfig(compare, 'op', '>=');
    store().setLiteral(compare, 'a', 5);
    store().setLiteral(compare, 'b', 3);

    expect(render()).toContain('if ((5 >= 3)) {');
  });
});

describe('every node in the registry generates something', () => {
  // §Phase 4 requires at minimum one golden test per node in the library.
  for (const def of allNodeDefs) {
    it(`${def.id} emits without throwing`, () => {
      useGraphStore.setState({ nodes: [], edges: [], past: [], future: [] });
      store().newProject();

      const nodeId = add(def.id, 240);
      if (def.kind === 'statement') {
        const loop = add('event.loop');
        connect(loop, 'exec-out:then', nodeId, 'exec-in');
      }

      const state = store();
      const result = generate(state.nodes, state.edges);
      expect(result.code).toContain('void loop()');
      expect(result.code.length).toBeGreaterThan(80);
    });
  }
});

describe('identifier handling', () => {
  it('sanitises names into valid C++ identifiers', () => {
    expect(sanitiseIdentifier('my sensor!')).toBe('my_sensor_');
    expect(sanitiseIdentifier('2fast')).toBe('_2fast');
    expect(sanitiseIdentifier('')).toBe('value');
    expect(sanitiseIdentifier('int')).toBe('int_');
    expect(sanitiseIdentifier('loop')).toBe('loop_');
  });

  it('suffixes colliding names', () => {
    const names = new NameAllocator();
    expect(names.allocate('speed')).toBe('speed');
    expect(names.allocate('speed')).toBe('speed2');
    expect(names.allocate('speed')).toBe('speed3');
  });

  it('prefixes internal temporaries so they cannot collide with user names', () => {
    const names = new NameAllocator();
    expect(names.allocateTemp('Analog Read')).toMatch(/^_af_/);
  });
});

describe('literal formatting', () => {
  it('gives float literals a decimal point so C++ does not do integer division', () => {
    expect(formatFloat(2)).toBe('2.0f');
    expect(formatFloat(2.5)).toBe('2.5f');
  });

  it('escapes quotes, backslashes, and newlines', () => {
    expect(escapeCppString('a"b\\c\nd')).toBe('"a\\"b\\\\c\\nd"');
  });
});
