// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Data Dashboard
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

#include "AwryLink.h"

int ch0 = 0;
int ch1 = 0;
int ch2 = 0;
int ch3 = 0;

// Variables exposed to the ArduForge dashboard.
static const AwryVar AWRY_VARS[] = {
  { "ch0", (void *)&ch0, AWRY_INT, true },
  { "ch1", (void *)&ch1, AWRY_INT, true },
  { "ch2", (void *)&ch2, AWRY_INT, true },
  { "ch3", (void *)&ch3, AWRY_INT, true },
};
static const char AWRY_HASH[] = "b9b5aafb";

void setup() {
  Serial.begin(115200);
  awrylink_begin(AWRY_VARS, 4, AWRY_HASH);
  // nothing connected
}

void loop() {
  awrylink_poll();
  static unsigned long _af_last_n7 = 0;
  if (millis() - _af_last_n7 >= (unsigned long)(50)) {
    _af_last_n7 = millis();
    ch0 = analogRead(A0);
    ch1 = analogRead(A1);
    ch2 = analogRead(A2);
    ch3 = analogRead(A3);
  }
}
