// ─────────────────────────────────────────────
//  Generated by ArduForge
//  Project: Potentiometer Fade
//  Board:   Arduino Uno (arduino:avr:uno)
// ─────────────────────────────────────────────

#include "AwryLink.h"

int brightness = 0;

// Variables exposed to the ArduForge dashboard.
static const AwryVar AWRY_VARS[] = {
  { "brightness", (void *)&brightness, AWRY_INT, true },
};
static const char AWRY_HASH[] = "66aa4bdb";

void setup() {
  Serial.begin(115200);
  awrylink_begin(AWRY_VARS, 1, AWRY_HASH);
  pinMode(9, OUTPUT);
  pinMode(9, OUTPUT);
}

void loop() {
  awrylink_poll();
  static unsigned long _af_last_n5 = 0;
  if (millis() - _af_last_n5 >= (unsigned long)(50)) {
    _af_last_n5 = millis();
    brightness = map(analogRead(A0), 0, 1023, 0, 255);
    analogWrite(9, brightness);
  }
}
